package com.lottery.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.mail.SimpleMailMessage;

@Configuration
public class EmailConfig {

	@Bean
    public SimpleMailMessage templateSimpleMessage() {
        SimpleMailMessage message = new SimpleMailMessage();
        //message.setText("This is the test email template for your email:\n%s\n");
        message.setText("<!DOCTYPE html>\r\n"
        		+ "<html>\r\n"
        		+ "\r\n"
        		+ "<head>\r\n"
        		+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
        		+ "\r\n"
        		+ "    <title>Lottery</title>\r\n"
        		+ "\r\n"
        		+ "    <style>\r\n"
        		+ "\r\n"
        		+ "        body {margin:0; padding:0; -webkit-text-size-adjust:none; -ms-text-size-adjust:none;} img{line-height:100%; outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;} a img{border: none;} #backgroundTable {margin:0; padding:0; width:100% !important; } a, a:link{color:#2A5DB0; text-decoration: underline;} table td {border-collapse:collapse;} span {color: inherit; border-bottom: none;} span:hover { background-color: transparent; }\r\n"
        		+ "\r\n"
        		+ "    </style>\r\n"
        		+ "\r\n"
        		+ "    <style>\r\n"
        		+ " .scalable-image img{max-width:100% !important;height:auto !important}.button a{transition:background-color .25s, border-color .25s}.button a:hover{background-color:#e1e1e1 !important;border-color:#0976a5 !important}@media only screen and (max-width: 400px){.preheader{font-size:12px !important;text-align:center !important}.header--white{text-align:center}.header--white .header__logo{display:block;margin:0 auto;width:118px !important;height:auto !important}.header--left .header__logo{display:block;width:118px !important;height:auto !important}}@media screen and (-webkit-device-pixel-ratio), screen and (-moz-device-pixel-ratio){.sub-story__image,.sub-story__content{display:block\r\n"
        		+ " !important}.sub-story__image{float:left !important;width:200px}.sub-story__content{margin-top:30px !important;margin-left:200px !important}}@media only screen and (max-width: 550px){.sub-story__inner{padding-left:30px !important}.sub-story__image,.sub-story__content{margin:0 auto !important;float:none !important;text-align:center}.sub-story .button{padding-left:0 !important}}@media only screen and (max-width: 400px){.featured-story--top table,.featured-story--top td{text-align:left}.featured-story--top__heading td,.sub-story__heading td{font-size:18px !important}.featured-story--bottom:nth-child(2) .featured-story--bottom__inner{padding-top:10px\r\n"
        		+ " !important}.featured-story--bottom__inner{padding-top:20px !important}.featured-story--bottom__heading td{font-size:28px !important;line-height:32px !important}.featured-story__copy td,.sub-story__copy td{font-size:14px !important;line-height:20px !important}.sub-story table,.sub-story td{text-align:center}.sub-story__hero img{width:100px !important;margin:0 auto}}@media only screen and (max-width: 400px){.footer td{font-size:12px !important;line-height:16px !important}}\r\n"
        		+ "     @media screen and (max-width:600px) {\r\n"
        		+ "    table[class=\"columns\"] {\r\n"
        		+ "        margin: 0 auto !important;float:none !important;padding:10px 0 !important;\r\n"
        		+ "    }\r\n"
        		+ "    td[class=\"left\"] {\r\n"
        		+ "     padding: 0px 0 !important;\r\n"
        		+ "    </style>\r\n"
        		+ "\r\n"
        		+ "</head>\r\n"
        		+ "\r\n"
        		+ "<body style=\"background: #e1e1e1;font-family:Arial, Helvetica, sans-serif; font-size:1em;\"><style type=\"text/css\">\r\n"
        		+ "div.preheader \r\n"
        		+ "{ display: none !important; } \r\n"
        		+ "</style>\r\n"
        		+ "\r\n"
        		+ "    <table id=\"backgroundTable\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"background:#e1e1e1;\">\r\n"
        		+ "        <tr>\r\n"
        		+ "            <td class=\"body\" align=\"center\" valign=\"top\" style=\"background:#e1e1e1;\" width=\"100%\">\r\n"
        		+ "                <table cellpadding=\"0\" cellspacing=\"0\">\r\n"
        		+ "                    <tr>\r\n"
        		+ "                        <td width=\"640\">\r\n"
        		+ "                            </td>\r\n"
        		+ "                    </tr>\r\n"
        		+ "                    <tr>\r\n"
        		+ "                        <td class=\"main\" width=\"640\" align=\"center\" style=\"padding: 0 10px;\">\r\n"
        		+ "                            <table style=\"min-width: 100%; \" class=\"stylingblock-content-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"><tr><td class=\"stylingblock-content-wrapper camarker-inner\"><table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ " <tr>\r\n"
        		+ "  <td width=\"640\" align=\"left\">\r\n"
        		+ "   <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "    <tr>\r\n"
        		+ "     <td class=\"header header--left\" style=\"padding: 20px 10px;\" align=\"left\">\r\n"
        		+ "      \r\n"
        		+ "     </td>\r\n"
        		+ "    </tr>\r\n"
        		+ "   </table>\r\n"
        		+ "  </td>\r\n"
        		+ " </tr>\r\n"
        		+ "</table></td></tr></table><table style=\"min-width: 100%; \" class=\"stylingblock-content-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"><tr><td class=\"stylingblock-content-wrapper camarker-inner\"><table class=\"featured-story featured-story--top\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ " <tr>\r\n"
        		+ "  <td style=\"padding-bottom: 20px;\">\r\n"
        		+ "   <table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "    <tr>\r\n"
        		+ "     <td class=\"featured-story__inner\" style=\"background: #fff;\">\r\n"
        		+ "      <table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "       <tr>\r\n"
        		+ "        <td class=\"scalable-image\" width=\"640\" align=\"center\">\r\n"
        		+ "         <a></a>\r\n"
        		+ "        </td>\r\n"
        		+ "       </tr>\r\n"
        		+ "       <tr>\r\n"
        		+ "        <td class=\"featured-story__content-inner\" style=\"padding: 32px 30px 45px;\">\r\n"
        		+ "         <table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "          <tr>\r\n"
        		+ "           <td class=\"featured-story__heading featured-story--top__heading\" style=\"background: #fff;\" width=\"640\" align=\"left\">\r\n"
        		+ "            <table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "             <tr>\r\n"
        		+ "              <td style=\"font-family: Geneva, Tahoma, Verdana, sans-serif; font-size: 22px; color: #464646;\" width=\"400\" align=\"left\">\r\n"
        		+ "               <a style=\"text-decoration: none; color: #464646;\">Sorteo %s</a>\r\n"
        		+ "              </td>\r\n"
        		+ "             </tr>\r\n"
        		+ "            </table>\r\n"
        		+ "           </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "          <tr>\r\n"
        		+ "           <td class=\"featured-story__copy\" style=\"background: #fff;\" width=\"640\" align=\"center\">\r\n"
        		+ "            <table cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "             <tr>\r\n"
        		+ "              <td style=\"font-family: Geneva, Tahoma, Verdana, sans-serif; font-size: 16px; line-height: 22px; color: #555555; padding-top: 16px;\" align=\"left\">\r\n"
        		+ "                El numero asignado es <b>%s</b> con un costo de <b>$%s</b>. <br><br>\r\n"
        		+ "                Favor de realizar el pago a la cuenta XXXX-XXXX-XXXX-XXXX y enviar el comprobante al correo comprobante@lottery.com.mx indicando el nombre del sorteo y el numero pagado.\r\n"
        		+ "              </td>\r\n"
        		+ "             </tr>\r\n"
        		+ "            </table>\r\n"
        		+ "           </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "         </table>\r\n"
        		+ "        </td>\r\n"
        		+ "       </tr>\r\n"
        		+ "      </table>\r\n"
        		+ "     </td>\r\n"
        		+ "    </tr>\r\n"
        		+ "   </table>\r\n"
        		+ "  </td>\r\n"
        		+ " </tr>\r\n"
        		+ "</table></td></tr></table>\r\n"
        		+ "                   \r\n"
        		+ "                   \r\n"
        		+ "                </table>\r\n"
        		+ "            </td>\r\n"
        		+ "        </tr>\r\n"
        		+ "    </table>\r\n"
        		+ "\r\n"
        		+ "    <!-- Exact Target tracking code -->\r\n"
        		+ "   \r\n"
        		+ "  \r\n"
        		+ "</body>\r\n"
        		+ "</html>");
        return message;
    }
	
}
